// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WailsApp from "./wailsapp.js";
export {
    WailsApp
};

export {
    Config
} from "./models.js";
