// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config 配置结构
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("HomeSSID" in $$source)) {
            /**
             * 家庭WiFi的SSID
             * @member
             * @type {string}
             */
            this["HomeSSID"] = "";
        }
        if (!("StaticIP" in $$source)) {
            /**
             * 静态IP地址
             * @member
             * @type {string}
             */
            this["StaticIP"] = "";
        }
        if (!("Gateway" in $$source)) {
            /**
             * 网关地址
             * @member
             * @type {string}
             */
            this["Gateway"] = "";
        }
        if (!("DNS" in $$source)) {
            /**
             * DNS服务器地址
             * @member
             * @type {string}
             */
            this["DNS"] = "";
        }
        if (!("AutoStart" in $$source)) {
            /**
             * 是否开机自启
             * @member
             * @type {boolean}
             */
            this["AutoStart"] = false;
        }
        if (!("IPMode" in $$source)) {
            /**
             * IP模式: adaptive(自适应), dynamic(动态IP), static(静态IP)
             * @member
             * @type {string}
             */
            this["IPMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * NetworkStatus 网络状态结构
 */
export class NetworkStatus {
    /**
     * Creates a new NetworkStatus instance.
     * @param {Partial<NetworkStatus>} [$$source = {}] - The source object to create the NetworkStatus.
     */
    constructor($$source = {}) {
        if (!("WiFiName" in $$source)) {
            /**
             * WiFi名称
             * @member
             * @type {string}
             */
            this["WiFiName"] = "";
        }
        if (!("WiFiConnected" in $$source)) {
            /**
             * WiFi连接状态
             * @member
             * @type {boolean}
             */
            this["WiFiConnected"] = false;
        }
        if (!("IPAddress" in $$source)) {
            /**
             * 当前IP地址
             * @member
             * @type {string}
             */
            this["IPAddress"] = "";
        }
        if (!("Gateway" in $$source)) {
            /**
             * 当前网关
             * @member
             * @type {string}
             */
            this["Gateway"] = "";
        }
        if (!("GatewayReachable" in $$source)) {
            /**
             * 网关是否可达
             * @member
             * @type {boolean}
             */
            this["GatewayReachable"] = false;
        }
        if (!("DNS" in $$source)) {
            /**
             * 当前DNS
             * @member
             * @type {string}
             */
            this["DNS"] = "";
        }
        if (!("DNSReachable" in $$source)) {
            /**
             * DNS是否可达
             * @member
             * @type {boolean}
             */
            this["DNSReachable"] = false;
        }
        if (!("IPAssignment" in $$source)) {
            /**
             * IP分配方式: "自动(DHCP)" 或 "手动"
             * @member
             * @type {string}
             */
            this["IPAssignment"] = "";
        }
        if (!("DNSAssignment" in $$source)) {
            /**
             * DNS分配方式: "自动(DHCP)" 或 "手动"
             * @member
             * @type {string}
             */
            this["DNSAssignment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkStatus(/** @type {Partial<NetworkStatus>} */($$parsedSource));
    }
}
