// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config 配置结构
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("HomeSSID" in $$source)) {
            /**
             * 家庭WiFi的SSID
             * @member
             * @type {string}
             */
            this["HomeSSID"] = "";
        }
        if (!("StaticIP" in $$source)) {
            /**
             * 静态IP地址
             * @member
             * @type {string}
             */
            this["StaticIP"] = "";
        }
        if (!("Gateway" in $$source)) {
            /**
             * 网关地址
             * @member
             * @type {string}
             */
            this["Gateway"] = "";
        }
        if (!("DNS" in $$source)) {
            /**
             * DNS服务器地址
             * @member
             * @type {string}
             */
            this["DNS"] = "";
        }
        if (!("AutoStart" in $$source)) {
            /**
             * 是否开机自启
             * @member
             * @type {boolean}
             */
            this["AutoStart"] = false;
        }
        if (!("IPMode" in $$source)) {
            /**
             * IP模式: adaptive(自适应), dynamic(动态IP), static(静态IP)
             * @member
             * @type {string}
             */
            this["IPMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}
