// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsApp struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckAndSwitch 检查网络状态并切换配置
 * @returns {$CancellablePromise<void>}
 */
export function CheckAndSwitch() {
    return $Call.ByID(1536615958);
}

/**
 * GetConfig 返回当前配置
 * @returns {$CancellablePromise<$models.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(142969655).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Greet returns a greeting for the given name
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(3132339404, name);
}

/**
 * HideWindow 隐藏窗口（由前端调用，用于拦截窗口关闭）
 * @returns {$CancellablePromise<void>}
 */
export function HideWindow() {
    return $Call.ByID(1124032883);
}

/**
 * IsConnectedToHomeNetwork 检查是否连接到家庭局域网
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConnectedToHomeNetwork() {
    return $Call.ByID(3473874770);
}

/**
 * IsSideRouterReachable 检查旁路由是否可达
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSideRouterReachable() {
    return $Call.ByID(3509736940);
}

/**
 * OpenLocationSettings 打开位置设置页面
 * @returns {$CancellablePromise<void>}
 */
export function OpenLocationSettings() {
    return $Call.ByID(2235867645);
}

/**
 * SwitchToAdaptive 切换到自适应IP模式
 * @returns {$CancellablePromise<void>}
 */
export function SwitchToAdaptive() {
    return $Call.ByID(1915832240);
}

/**
 * SwitchToDHCP 切换到动态IP模式
 * @returns {$CancellablePromise<void>}
 */
export function SwitchToDHCP() {
    return $Call.ByID(362025089);
}

/**
 * SwitchToStatic 切换到静态IP模式
 * @returns {$CancellablePromise<void>}
 */
export function SwitchToStatic() {
    return $Call.ByID(643172);
}

/**
 * UpdateConfig 保存配置 & 应用新配置
 * @param {$models.Config | null} config
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(config) {
    return $Call.ByID(1599545108, config);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
