// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAndSwitch():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function Greet(arg1:string):Promise<string>;

export function IsConnectedToHomeNetwork():Promise<boolean>;

export function IsSideRouterReachable():Promise<boolean>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SwitchToDHCP():Promise<void>;

export function SwitchToStatic():Promise<void>;
