// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndSwitch() {
  return window['go']['main']['WailsApp']['CheckAndSwitch']();
}

export function GetConfig() {
  return window['go']['main']['WailsApp']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['WailsApp']['Greet'](arg1);
}

export function IsConnectedToHomeNetwork() {
  return window['go']['main']['WailsApp']['IsConnectedToHomeNetwork']();
}

export function IsSideRouterReachable() {
  return window['go']['main']['WailsApp']['IsSideRouterReachable']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['WailsApp']['SaveConfig'](arg1);
}

export function SwitchToDHCP() {
  return window['go']['main']['WailsApp']['SwitchToDHCP']();
}

export function SwitchToStatic() {
  return window['go']['main']['WailsApp']['SwitchToStatic']();
}
